version: '3'
services:
  webserver:
    build: .
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      DEBUG: 'true'
      MYSQL_DB_CONNECTION: mysql  # Use the service name defined below for MySQL connection
      MYSQL_DB_NAME: food
      MYSQL_USER: root
      MYSQL_PASSWORD: " "  # Adjust as per your MySQL configuration
      SITE_URL: http://localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: " "  # Same as MySQL root password

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: food
      MYSQL_ROOT_PASSWORD: " "  # Replace with your MySQL root password
